### ISSUE TITLE
Compound reference fails for Job

### ISSUE THREAD

**Issue by tayknight** [avendesora/pythonbible#77]
These work as expected
bible.get_references('Ezra 1:1-Ezra 1:3')
bible.get_references('Job 1:1-3')

This doesn't
bible.get_references('Job 1:1-Job 1:3')

**Comment by tayknight** [comment]
Looks like it is failing after it matches Job and the regex gets to John. John's regex is 
`JOHN_REGULAR_EXPRESSION = "(John" r"|Joh\.*" r"|Jhn\.*" r"|Jo\.*" r"|Jn\.*)"`
is matching on Jo\\.*

**Comment by avendesora** [comment]
Thanks for catching that. I'll work on getting that fixed ASAP.

**Comment by avendesora** [comment]
This should be fixed in pythonbible version 0.8
