### ISSUE TITLE
ASV data has incomplete bible

### ISSUE THREAD

**Issue by rswhiting** [avendesora/pythonbible#89]
In `pythonbible/bible/data/asv/verses.json` only the first line of each verse exists. For example, Psalm 1:1 (19001001) only contains "Blessed is the man that walketh not in the counsel of the wicked," and not the full "Blessed is the man that walketh not in the counsel of the wicked, Nor standeth in the way of sinners, Nor sitteth in the seat of scoffers: "

I suspect this is due to the newlines in the poetic or multi-line verses. This is a pretty major issue because large chunks of the bible are missing with no indication that something failed. To be clear: this is a data storage issue, not a problem with the code itself.

**Comment by avendesora** [comment]
That is a major issue. Thanks for pointing it out. The next release of pythonbible, which should be coming out this month (possibly this week), is completely changing how that data is stored and used; and, thankfully, it seems to have resolved this particular issue. I wouldn't recommend using it yet as it's still being tested, but if you want to take a look, you can see the code for the next release in this pull request: https://github.com/avendesora/pythonbible/pull/86

Thanks again for letting me know about this issue. I'm trying to formulate a plan for thoroughly testing the accuracy of the storing/formatting/displaying of all the scripture text. I'll definitely need to have that level of testing before the 1.0 release of pythonbible.

**Comment by rswhiting** [comment]
I discovered [this repo](https://github.com/scrollmapper/bible_databases), and it may be useful to just take their json or xml (they have a mysql option that I'm currently pursuing). The project I'm working on may also benefit from their cross-references db table.
